/**
 * Suggested rig names. Deadpan first names, McRidersons, and the sort of
 * thing you would write in a bothy book. One is picked at random whenever
 * a new bike needs calling something.
 */

const FIRST = [
  'Graeme', 'Nigel', 'Keith', 'Brenda', 'Malcolm', 'Denise', 'Trevor', 'Sharon',
  'Gordon', 'Linda', 'Barry', 'Moira', 'Derek', 'Janice', 'Clive', 'Pauline',
  'Norman', 'Gladys', 'Terry', 'Maureen', 'Colin', 'Beverley', 'Stewart', 'Yvonne',
  'Duncan', 'Sheila', 'Craig', 'Carol', 'Alistair', 'Lynne', 'Hamish', 'Morag',
  'Ewan', 'Fiona', 'Iain', 'Kirsty', 'Fraser', 'Shona', 'Callum', 'Eilidh',
  'Dougie', 'Mhairi', 'Rab', 'Senga', 'Wee Man', 'Big Man', 'Uncle Ken',
  'Auntie Pat', 'Our Kevin', 'Your Dave', 'That Neil', 'Just Steve',
  'Plain John', 'Ordinary Pete', 'Nobody Special', 'Whatshisname',
  'Thingy', 'Whatsit', 'Him Indoors', 'Her Outdoors', 'The Other One',
  'Mate', 'Pal', 'Chief', 'Boss', 'Gaffer', 'Skip', 'Ref', 'Coach',
  'Dad', 'Mum', 'Grandad', 'Nana', 'The In-Laws', 'Next Door',
  'The Postie', 'The Milkman', 'The Vicar', 'The Scout Leader',
  'Mr Tuesday', 'Mrs Weekend', 'Sir Lunchalot', 'Lady Puncture',
  'Captain Sensible', 'Private Idaho', 'Major Problem', 'General Nuisance',
  'Admiral Snackbar', 'Commodore Bidon', 'Sgt Inner Tube', 'Cpl Cafe Stop',
];

const MC_LEFT = [
  'Ridey', 'Packy', 'Baggy', 'Spoke', 'Chainy', 'Pedaly', 'Bivvy', 'Muddy',
  'Gravely', 'Derpy', 'Tubey', 'Saddle', 'Forky', 'Stemmy', 'Bidony', 'Rollie',
  'Bothy', 'Pannier', 'Wedgey', 'Caggy', 'Pump', 'Patchy', 'Clicky', 'Creaky',
];

const MC_RIGHT = [
  'Riderson', 'Packface', 'Bags', 'Spokeson', 'Chainface', 'Pedalson',
  'Biverson', 'Mudface', 'Gravelface', 'Tubeson', 'Saddleson', 'Forkface',
  'Stemson', 'Bidonface', 'Rollface', 'Bothyson', 'Pannierson', 'Wedgeson',
  'McLunch', 'McSpoke', 'McBivvy', 'McMidge', 'McHill', 'McGate',
];

const HAND = [
  'Tour de Farce', 'Spoke Too Soon', 'Chain Reaction', 'Gear Fear',
  'Pedal to the Medal', 'Brake Dancing', 'Handlebar Hemingway',
  'The Full Gas', 'Bonk Force One', 'Café Stop Forever',
  'One More Gate', 'Just Over This Hill', 'Nearly There',
  'I Can See the Car', 'We Should Have Turned Left',
  'The Map Was Fine', 'The Map Was Not Fine', 'Wrong OS Sheet',
  'Folded It Wrong', 'North Is That Way', 'North Is the Other Way',
  'Follow the River', 'Which River', 'The Pub Is Shut',
  'The Pub Was Shut', 'The Shop Closes at Four', 'No Cake Left',
  'They Have Stopped Doing Chips', 'Two Teas Please',
  'A Scone If You Have One', 'Make It a Pot', 'I Will Have What He Is Having',
  'The Midges Knew', 'The Midges Always Know', 'Headnet Weather',
  'Cleg Season', 'Tick Check', 'Damp in the Toes',
  'Damp in the Soul', 'Both Socks Wet', 'The Hero Layer',
  'The Panic Layer', 'The Layer I Should Have Worn',
  'It Said Sunny', 'It Always Says Sunny', 'A Bit Fresh',
  'Bracing', 'Character Building', 'Good for the Complexion',
  'Type Two Fun', 'Type Three Actually', 'We Will Laugh Later',
  'We Are Not Laughing Yet', 'Remember This Fondly',
  'The Unscheduled Bivvy', 'The Scheduled Bivvy That Was Not',
  'Bothy Book Hero', 'Bothy Book Villain', 'Left a Drawing',
  'Ate the Emergency Chocolate', 'There Was No Emergency',
  'There Was an Emergency', 'The Jelly Babies Are Strategic',
  'Last Jelly Baby', 'First Jelly Baby', 'Third Breakfast',
  'Second Lunch', 'Linner', 'Dunch', 'A Serious Snack',
  'The Mystery Click', 'The Mystery Creak', 'The Mystery Smell',
  'It Came From the Bottom Bracket', 'Do Not Look at the Chain',
  'I Just Degreased That', 'I Will Degrease That',
  'A Professional Standard of Filth', 'Race Weight Mud',
  'Aero Mud', 'Fashion Mud', 'Heirloom Mud',
  'The Optimistic Inner Tube', 'The Pessimistic Patch',
  'The Spare That Was Not Spare', 'The Pump That Fits a Different Valve',
  'Presta at a Schrader Party', 'Schrader in a Presta World',
  'Twenty PSI of Hope', 'Forty PSI of Lies',
  'The Seatpack of Holding', 'The Bar Roll of Secrets',
  'The Frame Bag of Holding Also', 'What Is in the Stem Bag',
  'Do Not Open the Stem Bag', 'The Stem Bag Is Soup',
  'Bidon of Despair', 'Bidon of Triumph', 'The Warm Bidon',
  'The One That Leaks', 'The Good Bottle', 'The Other Bottle',
  'Pannier Anxiety', 'Pannier Pride', 'A Sensible Load',
  'An Insensible Load', 'Who Packed This', 'I Packed This',
  'The Long Way Round', 'The Longer Way Round', 'The Scenic Disaster',
  'A Shortcut', 'A Shortcut Allegedly', 'As the Crow Flies We Are Lost',
  'Kilometres Are Longer Today', 'Miles Are Worse',
  'A Gentle 80', 'A Relaxed Century', 'Just a Spin',
  'Easy Day', 'Recovery Ride', 'I Thought This Was Flat',
  'That Was Not on the Profile', 'The Steep Bit',
  'The Other Steep Bit', 'The Steep Bit They Did Not Mention',
  'Freewheeling as a Personality', 'Walking as a Tactic',
  'The Honourable Dismount', 'The Strategic Hike-a-Bike',
  'Carry the Bike a Minute', 'Carry the Bike an Hour',
  'Why Is There a Stile', 'Why Are There Seven Stiles',
  'The Gate of No Latch', 'The Gate of Two Latches',
  'A Very British Right of Way', 'A Path in Theory',
  'Bridleway Energy', 'Footpath Energy', 'Tarmac at Last',
  'Tarmac Too Soon', 'Gravel Adjacent', 'Gravel in Spirit',
  'Roadish', 'Pathish', 'A Bit Chunkier Than Expected',
  'Chunky Monkey', 'Potato Field', 'The Sandpit',
  'Baby Heads', 'Not Baby Heads', 'Actually Baby Heads',
  'Washboards of Character', 'Corrugations of the Soul',
  'Tailwind Home', 'Headwind Home', 'Crosswind Always',
  'The Wind Has Opinions', 'The Wind Is Wrong',
  'Drafting a Tractor', 'Drafting a Cow', 'Drafting Shame',
  'KOM of the Car Park', 'QOM of the Lay-by',
  'Strava Can Never Know', 'Strava Already Knows',
  'Private Activity', 'I Will Upload It Tomorrow',
  'The Battery Died at the Good Bit', 'No Signal and Fine With It',
  'Beep', 'Beep Beep', 'A Considered Beep',
  'On Your Right', 'On Your Left', 'Sorry Mate',
  'Cheers Mate', 'Nice Bike', 'Is That a Riv?',
  'Nice Bags', 'What Bags Are Those', 'Apidura Tax',
  'Ortlieb Energy', 'A Very Serious Roll Top',
  'Waxed Canvas Weather', 'X-Pac Flex', 'Cordura Forever',
  'The Expedition That Was Not', 'The Overnighter That Became Three',
  'The Day Ride That Lied', 'Touring Adjacent',
  'Bikepacking-ish', 'Just Camping With a Bicycle',
  'A Bicycle That Camps', 'A Tent That Rides',
  'Sleeps Two if You Argue', 'Sleeps One Comfortably',
  'The 3am Reckoning', 'The 5am Optimism',
  'Dew Point', 'Condensation Nation', 'A Wet Pillow Situation',
  'The Bivvy Bag Sermon', 'Groundsheet Philosophy',
  'Pegs I Did Not Bring', 'Guy Lines of Theseus',
  'The Stove That Would Not', 'The Stove That Would',
  'A Cup of Something Hot', 'A Cup of Something Warm',
  'A Cup of Something', 'Just Add Water',
  'Dehydrated Victory', 'Dehydrated Regret',
  'Noodles Again', 'Noodles Still', 'A Heroic Porridge',
  'Salty Hands', 'Suncream Eyes', 'Chamois Matters',
  'The Pad Is Fine', 'The Pad Is Not Fine',
  'Saddle Time', 'Saddle Sore but Spiritually Well',
  'Numb but Committed', 'I Can Still Feel My Hands',
  'I Cannot Feel My Hands', 'Shake Them Out',
  'Eat Now', 'Eat More', 'Eat Again',
  'Salt Cap', 'Caffeine Strategy', 'A Tactical Haribo',
  'The Emergency Babybel', 'The Ceremonial Babybel',
  'A Dignified Scotch Egg', 'The Lay-by Banquet',
  'Petrol Station Sushi', 'Garage Forecourt Risotto',
  'A Meal Deal on a Mountain', 'Protein of Unclear Origin',
  'The Last Train', 'We Have Missed the Last Train',
  'A Bus That Exists on Paper', 'Hitching with Dignity',
  'Calling a Friend', 'Calling Mum', 'Calling It',
  'Tomorrow We Ride', 'Tomorrow We Sleep',
  'Same Again Tomorrow', 'Never Again Tomorrow',
  'Annual Mistake', 'Weekly Ritual', 'Daily Practice',
  'This Is Fine', 'This Is Grand', 'This Is Pure',
  'Lovely', 'Magic', 'Quality', 'Deadly', 'Savage',
  'A Result', 'A Session', 'A Mission', 'A Situation',
  'Absolute Scenes', 'Quiet Scenes', 'No Scenes',
  'Send It', 'Do Not Send It', 'We Sent It',
  'Full Gas Then Cake', 'Full Cake Then Gas',
  'Marginal Gains Cake', 'Aero Scone',
  'Wind Tunnel of the Soul', 'CdA of Shame',
  'Watts I Do Not Have', 'Watts I Pretend I Have',
  'A Very Honest 180 Watts', 'A Theatrical 300',
  'Spin to Win', 'Mash to Lose', 'Seated Forever',
  'Out of the Saddle for Show', 'Looking Back for Style',
  'Never Look Back', 'Always Look Back',
  'The Group Has Gone', 'I Am the Group',
  'Mechanical Sympathy', 'Mechanical Apathy',
  'A Click I Will Ignore', 'A Click I Should Not Ignore',
  'It Will Be Fine', 'It Was Not Fine',
  'Hold My Bidon', 'Hold My Map', 'Hold My Nerve',
  'See You at the Top', 'See You at the Bottom',
  'See You at the Cafe', 'See You Never',
  'After You', 'No After You', 'I Insist',
  'Ladies First', 'Gravity First', 'Cake First',
  'The Sunday Best', 'The Tuesday Worst',
  'Bank Holiday Energy', 'School Run Energy',
  'Dawn Patrol', 'Dusk Patrol', 'Lunch Patrol',
  'Golden Hour', 'Grey Hour', 'Midge Hour',
  'Civil Twilight', 'Uncivil Twilight',
  'Blue Hour on a Green Lane', 'Pink Sky Warning',
  'Red Sky Delight', 'No Sky Just Cloud',
  'A Cloud With Opinions', 'A Hill With Opinions',
  'A Cow With Opinions', 'The Cow Has Right of Way',
  'Negotiating With Sheep', 'A Diplomatic Lamb',
  'Horse Girls Ahead', 'Dog on a Long Lead',
  'Dog on No Lead', 'The Dog Is Fine',
  'The Dog Is Not Fine', 'Good Dog', 'Bad Gate',
  'Nice View Though', 'What View', 'Trust the Process',
  'Trust the Legs', 'Do Not Trust the Legs',
  'Legs Have Left the Chat', 'Heart Rate Has Thoughts',
  'Zone Two Forever', 'Zone Five by Accident',
  'A Conversational Pace', 'A Monologue Pace',
  'I Cannot Talk', 'I Can Only Talk',
  'Saving Myself', 'For What', 'For the Cake',
  'For the Photo', 'For the Story',
  'This Will Make a Great Story', 'This Is the Story',
  'Do Not Tell Anyone', 'Tell Everyone',
  'Put It in the Bothy Book', 'Leave No Trace Except This Name',
  'Packed Light', 'Packed Feelings', 'Packed a Whole Personality',
  'One Bag Too Many', 'One Bag Too Few',
  'The Correct Number of Bags Is More',
  'The Correct Number of Bags Is Fewer',
  'A Considered Loadout', 'An Emotional Loadout',
  'Everything but the Kitchen Sink',
  'The Kitchen Sink Is in the Pannier',
  'I Brought a Book', 'I Brought the Wrong Book',
  'I Brought No Book', 'I Am the Book',
  'Audiobook Miles', 'Podcast Hills', 'Silence as a Feature',
  'Just the Chain', 'Just the Wind', 'Just the Midges',
  'A Private Concert of Clicks',
  'The Orchestra of the Drivetrain',
  'One Tooth at a Time', 'All the Teeth',
  'Granny Ring Wisdom', 'Big Ring Hubris',
  'A Tasteful 1x', 'A Chaotic 3x',
  'I Missed a Shift', 'I Meant to Do That',
  'Dropped It', 'Picked It Up With Dignity',
  'The Quietest Mechanical', 'The Loudest Silence',
  'A Very Small Disaster', 'A Medium Disaster',
  'A Learning Experience', 'A Teaching Moment for the Universe',
  'Noted', 'Logged', 'Filed Under Weather',
  'Filed Under Terrain', 'Filed Under Character',
  'Will Ride Again', 'Would Not Ride Again',
  'Would Ride Again Immediately',
  'Same Time Next Week', 'Same Time Next Year',
  'See You in the Bothy', 'Save Me a Peg',
  'Kettle On', 'Kettle Off', 'Whose Kettle',
  'A Shared Mars Bar', 'A Negotiated Mars Bar',
  'The Last Square', 'I Was Saving That',
  'Fair Enough', 'Good Effort', 'Nice One',
  'Sound', 'Safe', 'Legend', 'Hero',
  'Absolute Unit of a Ride',
  'A Small but Honest Ride',
  'Barely a Ride', 'Definitely a Ride',
  'Ride Adjacent', 'Ride Curious',
  'Ridey McRiderson',
  'Packy McPackface',
  'Baggy McBagface',
  'Bivvy McBiverson',
  'Graeme Again',
  'Still Graeme',
  'Not Graeme',
  'Graeme 2',
  'The Original Graeme',
  'A Different Graeme',
];

const ADJ = [
  'Damp', 'Hero', 'Accidental', 'Unscheduled', 'Optimistic', 'Tragic',
  'Legendary', 'Quiet', 'Loud', 'Folded', 'Spare', 'Last', 'First',
  'Third', 'Wrong', 'Right', 'Mystery', 'Unclaimed', 'Steep', 'Mild',
  'Ferocious', 'Polite', 'Forgotten', 'Ceremonial', 'Provisional',
  'Reckless', 'Sensible', 'Timid', 'Feral', 'Honourable', 'Provisional',
  'Seasonal', 'Ritual', 'Tactical', 'Emotional', 'Administrative',
];

const NOUN = [
  'Sock', 'Multitool', 'Patch', 'Coffee', 'Puncture', 'Bothy',
  'OS Map', 'Headtorch', 'Spoke', 'Jelly Baby', 'Bivvy', 'Midge',
  'Pedal', 'Click', 'Sausage Roll', 'Inner Tube', 'Bidon', 'Pannier',
  'Seatpack', 'Bar Roll', 'Derailleur', 'Cassette', 'Pump',
  'Puncture Kit', 'Hill', 'Tailwind', 'Headwind', 'Cafe Stop',
  'Gate', 'Bridleway', 'Ford', 'Bothy Book', 'Buff', 'Overshoe',
  'Rain Cape', 'Stove', 'Spork', 'Mars Bar', 'Lay-by', 'Stile',
];

function unique(list) {
  return [...new Set(list.filter(Boolean))];
}

const generated = [];
for (const a of ADJ) {
  for (const n of NOUN) {
    generated.push(`The ${a} ${n}`);
  }
}

const mc = [];
for (const l of MC_LEFT) {
  for (const r of MC_RIGHT) {
    mc.push(`${l} Mc${r.replace(/^Mc/, '')}`);
  }
}

function take(arr, n) {
  const src = unique(arr);
  if (src.length <= n) return src;
  const out = [];
  const step = src.length / n;
  for (let i = 0; i < n; i++) out.push(src[Math.floor(i * step)]);
  return unique(out);
}

/** Stable 500. A mix of Graemes, McRidersons, and bothy-book titles. */
export const RIG_NAMES = unique([
  'Graeme',
  'Ridey McRiderson',
  'Packy McPackface',
  'Baggy McBagface',
  'Bivvy McBiverson',
  'Still Graeme',
  'The Original Graeme',
  ...FIRST,
  ...HAND,
  ...take(mc, 140),
  ...take(generated, 160),
]).slice(0, 500);

export function randomRigName() {
  return RIG_NAMES[(Math.random() * RIG_NAMES.length) | 0];
}
