import puppeteer from 'puppeteer-core';
const [,,URL,W,H,MOB,DIR] = process.argv;
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--hide-scrollbars','--enable-unsafe-swiftshader']});
const p=await b.newPage();
await p.setViewport({width:+W,height:+H,deviceScaleFactor:2,isMobile:MOB==='mobile',hasTouch:MOB==='mobile'});
await p.goto(URL,{waitUntil:'domcontentloaded',timeout:60000});
await p.waitForFunction('window.__READY_DONE === true',{timeout:60000}).catch(()=>{});
const w=(ms=900)=>new Promise(r=>setTimeout(r,ms));
const click=async s=>{await p.evaluate(x=>document.querySelector(x)?.click(),s); await w(1100);};
await w(1300);
await p.screenshot({path:`${DIR}/01-home.png`});
await click('.home-btn.is-primary');
await p.screenshot({path:`${DIR}/02-empty.png`});
await click('.btn.quiet');                    // Surprise me
await p.screenshot({path:`${DIR}/03-loaded.png`});
await click('.bag-card:not(.unfit)');
await p.screenshot({path:`${DIR}/04-bagsheet.png`});
await p.evaluate(()=>document.querySelector('.sheet-close')?.click()); await w();
await click('.add-bag');
await p.evaluate(()=>{const n=[...document.querySelectorAll('.mount-btn')].find(x=>/Handlebar roll/i.test(x.textContent)); n?.click();}); await w(1200);
await p.screenshot({path:`${DIR}/05-catalogue.png`});
await p.evaluate(()=>document.querySelector('.sheet-close')?.click()); await w();
await click('.acct-btn');
await p.screenshot({path:`${DIR}/06-rigs.png`});
await p.evaluate(()=>document.querySelector('.sheet-close')?.click()); await w();
await p.evaluate(()=>{const a=window.app;a.bags.randomKit(3);a.rigs.save('Highland overnighter');a.bags.randomKit(9);a.rigs.save('Race setup');a.ui?.sync?.();}); await w();
await click('.home-up');
await click('.home-btn:not(.is-primary)');
await p.screenshot({path:`${DIR}/07-gallery.png`});
await b.close(); console.log('captured to',DIR);
