import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--hide-scrollbars','--enable-unsafe-swiftshader']});
const p=await b.newPage();
await p.setViewport({width:1440,height:900,deviceScaleFactor:1});
await p.goto('http://localhost:8735/index.html',{waitUntil:'domcontentloaded'});
await p.waitForFunction('window.__READY_DONE === true',{timeout:30000});
const w=(ms)=>new Promise(r=>setTimeout(r,ms));
await w(1300);
await p.evaluate(()=>window.app.menu.go('loadouts')); await w(1700);
await p.evaluate(()=>document.querySelector('.pr-btn.is-primary').click()); await w(1300);
const box=(sel)=>p.evaluate(s=>{const n=document.querySelector(s); if(!n) return null; const r=n.getBoundingClientRect();
  return {t:Math.round(r.top),l:Math.round(r.left),w:Math.round(r.width),h:Math.round(r.height)};},sel);
const rows=[];
rows.push(['panel (10 bags)', await box('.panel')]);
await p.evaluate(()=>{window.app.bags.clearAll(); window.app.ui.sync();}); await w(600);
rows.push(['panel (0 bags)',  await box('.panel')]);
await p.evaluate(()=>window.app.bags.randomKit(7)); await w(600);
rows.push(['panel (random)',  await box('.panel')]);
await p.evaluate(()=>document.querySelector('.add-bag')?.click()); await w(1200);
rows.push(['sheet: mounts',   await box('.sheet')]);
await p.evaluate(()=>document.querySelector('.mount-btn')?.click()); await w(1400);
rows.push(['sheet: catalogue',await box('.sheet')]);
await p.evaluate(()=>document.querySelector('.sheet-close')?.click()); await w(900);
await p.evaluate(()=>document.querySelector('.bag-card')?.click()); await w(1300);
rows.push(['sheet: bag',      await box('.sheet')]);
await b.close();
for(const [k,v] of rows) console.log(k.padEnd(20), v? `top ${String(v.t).padStart(4)}  left ${String(v.l).padStart(4)}  ${String(v.w).padStart(4)}x${String(v.h).padStart(4)}` : 'ABSENT');
