import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--hide-scrollbars','--enable-unsafe-swiftshader']});
const p=await b.newPage();
await p.setViewport({width:1440,height:900,deviceScaleFactor:2});
await p.goto('http://localhost:8735/index.html',{waitUntil:'domcontentloaded'});
await p.waitForFunction('window.__READY_DONE === true',{timeout:30000});
await new Promise(r=>setTimeout(r,1400));
await p.evaluate(()=>window.app.menu.go('loadouts'));
await new Promise(r=>setTimeout(r,1800));
await p.evaluate(()=>document.querySelector('.pr-btn.is-primary').click());
await new Promise(r=>setTimeout(r,1400));
await p.evaluate(()=>window.app.openWindTunnel());
await new Promise(r=>setTimeout(r,9000));
console.log(await p.evaluate(()=>document.querySelector('.aero-panel')?.innerText.slice(0,260)));
await p.screenshot({path:process.argv[2]});
await b.close(); console.log('saved');
